# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Installation
    displayName: 'Setting up'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    
    - script: |
        npm install
      displayName: 'npm install'
  
  - job: RunTests
    displayName: Run Tests
    steps:
    - script: |
        npm test
        echo "Test Execution Finished"
        if [ -f "report.html" ]; then
          echo "📄 Report created successfully"
        else
          echo "❌ Report was not created"
          exit 1
        fi
      displayName: 'npm run test'
