# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run test
    echo "Test Execution Finished"
    if [ -f "index.html" ]; then      
      git config --global user.email "darkensses@gmail.com"
      git config --global user.name "Jasiel Guillen"
      git add index.html
      git commit -m "Report generated $(Build.BuildNumber)"
      git push https://$(GITHUB_TOKEN)@github.com/Darkensses/playwright-cucumber-api-test.git HEAD:main
      echo "📄 Report created successfully"
    else
      echo "❌ Report was not created"
      exit 1
    fi
  displayName: 'npm run test'
